### PR TITLE
185 max min text for slider questions is not validated

### LINKED ISSUE #185: Max. / Min. Text for slider questions is not validated
The inputs are not validated correctly and cause the application to show an exception

### PR DESCRIPTION
**Pull request by aluapaula**

### CODE REVIEW

File: src/main/java/de/imi/mopat/validator/QuestionDTOValidator.java [hunk 1]
```diff
@@ -182,6 +182,15 @@ public void validate(final Object target, final Errors errors) {
                 break;
             }
             case SLIDER:
+                // [bt] tell the errors object that from now on the
```
Comment (ywarnecke) [inline src/main/java/de/imi/mopat/validator/QuestionDTOValidator.java]: This is actually not necessary.

The syntax 
```
case X:
case Y:
case Z: 
```
automatically applies the code below to all three cases

File: src/main/resources/message/messages.properties [hunk 2]
```diff
@@ -899,6 +899,7 @@ sliderAnswer.validator.stepsizeBiggerThanDifferenceMaxMin=The answer's step size
 sliderAnswer.validator.stepsizeLowerEqualZero=The answer's step size was <= 0
 sliderAnswer.validator.stepsizeWrongPattern=The answer's step size does not match the required pattern.
 sliderAnswer.validator.tooManySteps=There are more than 200 steps available. Alternatively you can also use the question type number input.
+sliderAnswer.validator.localizedMinimumText=The text is longer than 255 characters
```
Comment (ywarnecke) [inline src/main/resources/message/messages.properties]: Please rename the property if it is used for both minimum and maximum text

**Review by ywarnecke — CHANGES_REQUESTED** [review]

**Review by ywarnecke — APPROVED** [review]
